config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "places#index"
  resources :places
  resources :properties
  resources :property_form_steps
  resources :profiles, only: [ :edit, :update]
  scope "/users" do
    get "account_settings", to: "profiles#account_setting"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
  attr_accessor :current_step

  acts_as_taggable_on :rules
  belongs_to :user
  mount_uploaders :images, ImageUploader

  enum property_type: { house: 0, apartment: 1, barn: 2, boat: 3, cabin: 4, castle: 5, cave: 6, container: 7, dammuso: 8, dome: 9, earth_home: 10, farm: 11, guest_house: 12, hotel: 13, houseboat: 14, minsu: 15, riad: 16, ryokan: 17, tent:18, tower: 19, treehouse: 20}
  enum stay_area: { entire_place: 0, room: 1, shared_room: 2 }

  validates :property_type, :stay_area, :total_guest_capacity, :total_room, :total_bed, :total_bathroom, presence: true, on: [:create, :update]
  validates :facility, inclusion: { in: %w(Wifi Tv Kitchen Washer Free\ parking Paid\ parking Ac Pool Hot\ tub Piano Excercise\ equipment First\ aid\ kit Nothing), message: "%{value} is not allowed"}, if: -> { current_step?(:facility) }
  validates :description, presence: true, if: -> { current_step?(:about_place) }
  validates :house_name, :street_name, :city, :state, :pincode, :country_name, presence: true, if: -> { current_step?(:address_for_place) }
  validates :images, presence: true, if: -> { current_step?(:upload_image) }
  validates :price, comparison: { less_than_or_equal_to: 800000, message: "must be betwenn 500 to 800000" }, if: -> { current_step?(:make_best_price) } 

  def current_step?(step_key)
    current_step == step_key
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :access_token
  validates :first_name, :last_name, presence: true
  validates :phone_no, :driving_license_no, uniqueness: true, on: :update
  validates :phone_no, :gender, :driving_license_no, :date_of_birth, presence: true, on: :update
  validates :phone_no, length: { is:10 }, on: :update
  validates :phone_no, numericality: true, on: :update
  validates :driving_license_no, format: { with: /\A[A-Za-z0-9]{6,12}\z/, message: "Enter valid Driving License" }, on: :update
  validates :date_of_birth, comparison: { less_than: Date.today, message: "date can not be today"}, on: :update
  after_create :assign_default_role

  rolify
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable

  def assign_default_role
    self.add_role(:tourist) if self.roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password, :phone_no, :work, :gender, :pets, :driving_license_no, :date_of_birth)}
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    set_user
  end

  def update
    set_user
    if @user.update(profile_params)
      redirect_to root_path, notice: "Profile Updated successfully." 
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def account_setting; end

  private
  def profile_params
    params.require(:user).permit(:phone_no, :gender, :work, :pets, :driving_license_no, :date_of_birth)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index; end
  
  def show; end
  
  def new 
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    @progress = 0
    if @property.save
      redirect_to(controller: 'property_form_steps' , property_id: (@property.id).to_param)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
  end

  def destroy; end

  private
  def property_params
    params.require(:property).permit(:property_type, :stay_area, :total_guest_capacity, :total_room, :total_bed, :total_bathroom, :description, :rule_list, :house_name, :street_name, :city, :state, :pincode, :country_name, :price, :user_id, {images: []}, facility: [])
  end
end

app/controllers/property_form_steps_controller.rb
class PropertyFormStepsController < ApplicationController
  include Wicked::Wizard
  steps :place_type, :facility, :about_place, :address_for_place, :upload_image, :make_best_price

  def show
    unless params[:property_id].blank?
      session[:property_id] = params[:property_id]
    end

    case step
    when :place_type
      @prev = Rails.application.routes.recognize_path(request.referrer)
      if @prev[:controller] == "properties"
        skip_step
      end
    end

    set_progress
    set_property
    render_wizard
  end

  def update
    set_progress
    @property.current_step = step
    @property.update(property_params)
    render_wizard @property
  end

  private

  def property_params
    params.require(:property).permit(:property_type, :stay_area, :total_guest_capacity, :total_room, :total_bed, :total_bathroom, :description, :rule_list, :house_name, :street_name, :city, :state, :pincode, :country_name, :price, :user_id, images: [], facility: [])
  end

  def set_property
    @property = Property.find(session[:property_id])
  end

  def set_progress
    set_property
    if current_step?(:place_type)
      @progress = 0
    elsif current_step?(:facility)
      @progress = 1
    elsif current_step?(:about_place)
      @progress = 2
    elsif current_step?(:address_for_place)
      @progress = 3
    elsif current_step?(:upload_image)
      @progress = 4
    elsif current_step?(:make_best_price)
      @progress = 5
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/property_form_steps_helper.rb
module PropertyFormStepsHelper
end

app/views/homes/index.html.erb
<h1>Hello, <%= current_user.first_name %></h1>
Logged in as <strong><%= current_user.email %></strong>.
<%= link_to 'Add profile', edit_user_registration_path %> 
<%= button_to 'Logout', destroy_user_session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "authentication" %>
    <%= stylesheet_link_tag "progress_bar" %>
    <%# Boxicons CSS %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js" %>
  </head>
  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<div class="container card w-50 p-5 my-3 border">
  <h1 class="text-center">Profile Details</h1>
  <div class="form-control-solid">
    <%= form_with model: @user, url: profile_path do |form| %>
      <%= render "devise/shared/error_messages", resource: @user %>
      <div class="row mb-4">
        <div class="col">
          <div class="form-outline">
            <%= form.label :first_name %><br/>
            <%= form.text_field :first_name, id:"form3Example1", class:"form-control", autofocus: true, autocomplete: "first_name" %>
          </div>
        </div>
        <div class="col">
          <div class="form-outline">
            <%= form.label :last_name %><br/>
            <%= form.text_field :last_name, id:"form3Example2", class:"form-control", autocomplete: "last_name" %>
          </div>
        </div>
      </div>
      <div class="form-outline mb-4">
        <%= form.label :email %><br />
        <%= form.email_field :email, id:"form3Example3", class: "form-control",autocomplete: "email" %>
      </div>
      <%= form.label :phone_no, "Phone Number:" %>
      <%= form.text_field :phone_no, class:"form-control" %>
      <br>
      <div class="form-check">
        <%= form.label "Select Gender:" %><br>
        <%= form.radio_button :gender, "Male", class:"form-check-input" %>
        <%= form.label :for_male, "Male"%><br/>
        <%= form.radio_button :gender, "Female", class:"form-check-input" %>
        <%= form.label :for_female, "Female"%><br/>
        <%= form.radio_button :gender, "Others", class:"form-check-input" %>
        <%= form.label :for_others, "Others"%><br>
      </div>
      <br>
      <br>
      <%= form.label "Job occupation:" %>
      <%= form.text_field :work, class:"form-control" %><br>
      <%= form.label "Pets:" %>
      <%= form.text_field :pets, class:"form-control" %><br>
      <%= form.label "Driving License Number:" %>
      <%= form.text_field :driving_license_no, class: "form-control" %>
      <br>
      <%= form.label "Birth Date:" %>
      <div id="date-picker-example" class="md-form md-outline input-with-post-icon datepicker">
        <%= form.date_field :date_of_birth, class: "form-control" %>
      </div>
      <br>
      <%= form.hidden_field :access_token, value: "profile" %>
      <%= form.submit "Save",  class: "btn btn-primary" %><br>
    <% end %><br>
    <%= link_to "Back", places_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/profiles/account_setting.html.erb
<div class="container card w-50 p-4 my-3 border border-dark">
  <div class = "text-center" >
    <h2>Account Setting</h2>
  </div>
  <div>
    <h5>change account password</h5>
    <%= link_to "change password", edit_user_registration_path(params: { perform: 'change'}), class: "btn btn-sm btn-primary rounded py-2 px-4" %><br/>
    <br/>
    <h5>delete your account</h5>
    <%= link_to "delete account", edit_user_registration_path(params: { perform: 'delete'}), class: "btn btn-sm btn-primary rounded py-2 px-4" %><br/>
    <br/>
    <h5>signout from your account</h5>
    <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-sm btn-primary rounded py-2 px-4" %><br/><br/>
    <%= link_to "Back", places_path, class: "btn btn-sm btn-primary rounded py-2 px-4" %>
  </div>
</div>

app/views/profiles/edit.html.erb
<%= render "form" %>

app/views/properties/_form.html.erb
<%= render "property_form_steps/shared/progress_bar" %>
<div class="container card w-50 p-5 my-3 border">
  <h3 class="text-center">Property Type</h3>
  <div class="form-control-solid">
    <%= render partial: "property_form_steps/shared/form", locals: {path: properties_path, method: :post} %>
  </div>
</div>

app/views/properties/edit.html.erb
<%= render "form" %>

app/views/properties/index.html.erb
<h1>list of Properties</h1>

app/views/properties/new.html.erb
<% @progress = 0 %>
<%= render "form" %>

app/views/property_form_steps/about_place.html.erb
<%= render "property_form_steps/shared/progress_bar" %>
<div class="container card w-50 p-5 my-3 border">
  <h3 class="text-center">About Your Place</h3>
  <div class="form-control-solid">
    <h3>About Your Place</h3>
    <%= form_with model: @property, url: wizard_path, method: :patch do |form| %>
      <%= render "property_form_steps/shared/error_message" %>
      <div class="form-outline">
        <%= form.label :description %>
        <%= form.text_area :description, id:"form3Example3", class: "form-control"  %><br/>
      </div>
      <div class="form-outline">
        <%= form.label :rule %>
        <%= form.text_area :rule_list, id:"form3Example3", class: "form-control"  %><br/>
      </div>
      <%= form.submit "continue", class: "btn btn-primary" %>
      <%= link_to "Previous", previous_wizard_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/property_form_steps/address_for_place.html.erb
<%= render "property_form_steps/shared/progress_bar" %>
<div class="container card w-50 p-5 my-3 border">
  <h3 class="text-center">Address Of Your Place</h3>
  <%= render "property_form_steps/shared/error_message" %>
  <div class="form-control-solid">
    <%= form_with model: @property, url: wizard_path, method: :put do |form| %>
      <div class="row mb-4">
        <div class="col">
          <div class="form-outline">
            <%= form.label :house_name %>
            <%= form.text_field :house_name, id:"form3Example3", class: "form-control" %><br/>
          </div>
        </div>
        <div class="col">
          <div class="form-outline">
            <%= form.label :street_name %>
            <%= form.text_field :street_name, id:"form3Example3", class: "form-control" %><br/>
          </div>
        </div>
      </div>
      <div class="row mb-4">
        <div class="col">
          <div class="form-outline">
            <%= form.label :city %>
            <%= form.text_field :city, id:"form3Example3", class: "form-control" %><br/>
          </div>
        </div>
        <div class="col">
          <div class="form-outline">
            <%= form.label :state %>
            <%= form.text_field :state, id:"form3Example3", class: "form-control" %><br/>
          </div>
        </div>
      </div>
      <div class="row mb-4">
        <div class="col">
          <div class="form-outline">
            <%= form.label :pincode %>
            <%= form.text_field :pincode, id:"form3Example3", class: "form-control" %><br/>
          </div>
        </div>
        <div class="col">
          <div class="form-outline">
            <%= form.label :country_name %>
            <%= form.text_field :country_name, id:"form3Example3", class: "form-control" %><br/>
          </div>
        </div>
      </div>
      <%= form.submit "continue", class: "btn btn-primary" %>
      <%= link_to "Previous", previous_wizard_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/property_form_steps/facility.html.erb
<%= render "property_form_steps/shared/progress_bar" %>
<div class="container card w-50 p-5 my-3 border">
  <h3 class="text-center">Facility</h3>
  <%= render "property_form_steps/shared/error_message" %>
  <div class="form-control-solid">
    <%= form_with model: @property, url: wizard_path, method: :patch do |form| %>
      <% facilities = ['Wifi', 'Tv', 'Kitchen', 'Washer', 'Free parking', 'Paid parking', 'Ac', 'Pool', 'Hot tub', 'Piano', 'Excercise equipment', 'First aid kit', 'Nothing'] %>
      <h5>Select Atleast One</h5><br/>
      <% facilities.each do |facility| %>
        <div class="form-check">
          <%= form.check_box :facility, { multiple: true }, facility, false %>
          <%= form.label :facility, facility, class:"form-check-label", for:"flexCheckDefault" %><br/>
        </div>
      <% end %><br/>
      <%= form.submit "continue", class: "btn btn-primary" %>
      <%= link_to "Previous", previous_wizard_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/property_form_steps/make_best_price.html.erb
<%= render "property_form_steps/shared/progress_bar" %>
<div class="container card w-50 p-5 my-3 border">
  <h3 class="text-center">Set Best Price For Your Place</h3>
  <%= render "property_form_steps/shared/error_message" %>
  <div class="form-control-solid">
    <%= form_with model: @property, url: wizard_path, method: :patch do |form| %>
      <div class="form-outline w-25">
        <%= form.label :price %>
        <%= form.number_field :price, in: 500..800000, step: 100, id:"form3Example3", class: "form-control" %><br/>
      </div>
      <%= form.submit "continue", class: "btn btn-primary" %>
      <%= link_to "Previous", previous_wizard_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/property_form_steps/place_type.html.erb
<%= render "property_form_steps/shared/progress_bar" %>
<div class="container card w-50 p-5 my-3 border">
  <h3 class="text-center">Property Type</h3>
  <div class="form-control-solid">
  <%= @path = "wizard_path" %>
    <%= render partial: "property_form_steps/shared/form", locals: { path: wizard_path, method: :patch} %>
  </div>
</div>

app/views/property_form_steps/shared/_error_message.html.erb
<% if @property.errors.any? %>
  <div class="alert alert-danger" >
    <div id="error_explanation" data-turbo-cache="false">
      <ul>
        <% @property.errors.each do |message| %>
          <li><%= message.full_message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/property_form_steps/shared/_form.html.erb
<%= form_with model: @property, url: path, method: method do |form| %>
  <%= render "property_form_steps/shared/error_message" %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <div class="row mb-4">
    <div class="col">
      <div class="form-outline">
        <%= form.label :property_type, "Property type:" %>
        <%= form.select :property_type, Property.property_types.map{ |key, value| [key.titleize, key]} %>
      </div>
    </div>
    <div class="col">
      <div class="form-outline">
        <%= form.label :stay_area, "Stay area:" %>
        <%= form.select :stay_area, Property.stay_areas.map {|key, value| [key.titleize, key]} %>
      </div>
    </div>
  </div>
  <div class="row mb-4">
    <div class="col">
      <div class="form-outline">
        <%= form.label :total_guest_capacity, "Total guest capacity:" %>
        <%= form.number_field :total_guest_capacity, in: 1.0..1000, id:"form3Example3", class: "form-control" %><br/>
      </div>
    </div>
    <div class="col">
      <div class="form-outline">
        <%= form.label :total_room %>
        <%= form.number_field :total_room, in: 1.0..100, id:"form3Example3", class: "form-control" %><br/>
      </div>
    </div>
  </div>
  <div class="row mb-4">
    <div class="col">
      <div class="form-outline">
        <%= form.label :total_bed %>
        <%= form.number_field :total_bed, in: 1.0..300, id:"form3Example3", class: "form-control" %><br/>
      </div>
    </div>
    <div class="col">
      <div class="form-outline">
        <%= form.label :total_bathroom %>
        <%= form.number_field :total_bathroom, in: 1.0..100, id:"form3Example3", class: "form-control" %><br/>
      </div>
    </div>
  </div>
  <%= form.submit "Continue", class: "btn btn-primary" %>
<% end %>

app/views/property_form_steps/shared/_progress_bar.html.erb
<div class="row d-flex justify-content-center">
  <div >
    <ul id="progressbar" class="text-center">
      <li class="<%= @progress > 0 ? 'active step0' : 'step0' %>">Property Type</li>
      <li class="<%= @progress > 1 ? 'active step0' : 'step0' %>">Facility</li>
      <li class="<%= @progress > 2 ? 'active step0' : 'step0' %>">About Place</li>
      <li class="<%= @progress > 3 ? 'active step0' : 'step0' %>">Address Of Place</li>
      <li class="<%= @progress > 4 ? 'active step0' : 'step0' %>">Place Image</li>
      <li class="<%= @progress > 5 ? 'active step0' : 'step0' %>">Make Best Price For Place</li>
    </ul>
  </div>
</div>

app/views/property_form_steps/upload_image.html.erb
<%= render "property_form_steps/shared/progress_bar" %>
<div class="container card w-50 p-5 my-3 border">
  <h3 class="text-center">Upload Images</h3>
  <%= render "property_form_steps/shared/error_message" %>
  <div class="form-control-solid">
    <%= form_with model: @property, url: wizard_path, method: :patch do |form| %>
      <% 4.times do %>
        <%= form.file_field :images, multiple: true %><br/>
      <% end %><br/>
      <%= form.submit "continue", class: "btn btn-primary" %>
      <%= link_to "Previous", previous_wizard_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>